# docker-compose down && docker-compose -f docker-compose_dev.yml up --build -d
# show containers ip
# docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)

version: '2'
services:
  project:
    restart: always
    container_name: bot
    #image: telegrambot_project
    build:
      context: .
      dockerfile: Dockerfile_dev
    working_dir: /opt/project
    links:
      - postgres
    volumes:
      - ./:/opt/project
    ports:
      - "2225:22"
    command: /sbin/my_init


  data:
    restart: 'no'
    image: postgres:9.5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    command: echo "start data container"


  postgres:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_postgres
    #environment:
      #POSTGRES_PASSWORD: 'secret'
      #POSTGRES_DB: 'rsstelebot'
    volumes_from:
      - data
    ports:
      - "5432:5432"