# docker-compose stop && docker-compose rm -f && docker-compose build --no-cache project && docker-compose up -d

version: '2'
services:
  project:
    restart: always
    container_name: bot
    #image: telegrambot_project
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt/project
    links:
      - postgres
    volumes:
      - ./:/opt/project
    ports:
      - "2225:22"
    command: python3 ./rssbot.py &


  data:
    restart: 'no'
    image: postgres:9.5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    command: echo "start data container"


  postgres:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_postgres
    volumes_from:
      - data
    ports:
      - "5432:5432"